In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
project_file = files.upload()

Saving fifa21 raw data v2.csv to fifa21 raw data v2 (1).csv

In [ ]:
df = pd.read_csv('fifa21 raw data v2.csv', low_memory=False)

df

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,91,\n\n\n\nManchester City,...,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,91,\n\n\n\nParis Saint-Germain,...,High,Medium,5 ★,91,85,86,94,36,59,595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47,55,\n\n\n\nWuhan Zall,...,Medium,Medium,1 ★,64,28,26,38,48,51,NaN
18975,258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47,67,\n\n\n\nOldham Athletic,...,Medium,Medium,1 ★,64,40,48,49,35,45,NaN
18976,252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18,47,65,\n\n\n\nDerry City,...,Medium,Medium,1 ★,63,39,44,46,40,53,NaN
18977,243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20,47,57,\n\n\n\nDalian YiFang FC,...,Medium,Medium,1 ★,58,49,41,49,30,44,NaN
18978,252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47,57,\n\n\n\nDalian YiFang FC,...,Medium,Medium,1 ★,62,22,39,42,45,55,NaN

Take care of club column

In [ ]:
df["Club"].value_counts()

Club
No Club                           237
\n\n\n\nRC Celta                   33
\n\n\n\nEverton                    33
\n\n\n\nManchester United          33
\n\n\n\nLeicester City             33
                                 ...
\n\n\n\nBrisbane Roar              18
\n\n\n\nAdelaide United            18
\n\n\n\nMelbourne Victory          18
\n\n\n\nPerth Glory                18
\n\n\n\nCentral Coast Mariners     18
Name: count, Length: 682, dtype: int64

In [ ]:
df["Club"] = df["Club"].str.replace("\n", "")
df["Club"]

0               FC Barcelona
1                   Juventus
2            Atlético Madrid
3            Manchester City
4        Paris Saint-Germain
                ...
18974             Wuhan Zall
18975        Oldham Athletic
18976             Derry City
18977       Dalian YiFang FC
18978       Dalian YiFang FC
Name: Club, Length: 18979, dtype: object

In [ ]:
df["Club"].value_counts()

Club
No Club                   237
RC Celta                   33
Everton                    33
Manchester United          33
Leicester City             33
                         ...
Brisbane Roar              18
Adelaide United            18
Melbourne Victory          18
Perth Glory                18
Central Coast Mariners     18
Name: count, Length: 682, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 77 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                18979 non-null  int64
 1   Name              18979 non-null  object
 2   LongName          18979 non-null  object
 3   photoUrl          18979 non-null  object
 4   playerUrl         18979 non-null  object
 5   Nationality       18979 non-null  object
 6   Age               18979 non-null  int64
 7   ↓OVA              18979 non-null  int64
 8   POT               18979 non-null  int64
 9   Club              18979 non-null  object
 10  Contract          18979 non-null  object
 11  Positions         18979 non-null  object
 12  Height            18979 non-null  object
 13  Weight            18979 non-null  object
 14  Preferred Foot    18979 non-null  object
 15  BOV               18979 non-null  int64
 16  Best Position     18979 non-null  object
 17  Joined            18979 non-null  object
 18  Loan Date End     1013 non-null   object
 19  Value             18979 non-null  object
 20  Wage              18979 non-null  object
 21  Release Clause    18979 non-null  object
 22  Attacking         18979 non-null  int64
 23  Crossing          18979 non-null  int64
 24  Finishing         18979 non-null  int64
 25  Heading Accuracy  18979 non-null  int64
 26  Short Passing     18979 non-null  int64
 27  Volleys           18979 non-null  int64
 28  Skill             18979 non-null  int64
 29  Dribbling         18979 non-null  int64
 30  Curve             18979 non-null  int64
 31  FK Accuracy       18979 non-null  int64
 32  Long Passing      18979 non-null  int64
 33  Ball Control      18979 non-null  int64
 34  Movement          18979 non-null  int64
 35  Acceleration      18979 non-null  int64
 36  Sprint Speed      18979 non-null  int64
 37  Agility           18979 non-null  int64
 38  Reactions         18979 non-null  int64
 39  Balance           18979 non-null  int64
 40  Power             18979 non-null  int64
 41  Shot Power        18979 non-null  int64
 42  Jumping           18979 non-null  int64
 43  Stamina           18979 non-null  int64
 44  Strength          18979 non-null  int64
 45  Long Shots        18979 non-null  int64
 46  Mentality         18979 non-null  int64
 47  Aggression        18979 non-null  int64
 48  Interceptions     18979 non-null  int64
 49  Positioning       18979 non-null  int64
 50  Vision            18979 non-null  int64
 51  Penalties         18979 non-null  int64
 52  Composure         18979 non-null  int64
 53  Defending         18979 non-null  int64
 54  Marking           18979 non-null  int64
 55  Standing Tackle   18979 non-null  int64
 56  Sliding Tackle    18979 non-null  int64
 57  Goalkeeping       18979 non-null  int64
 58  GK Diving         18979 non-null  int64
 59  GK Handling       18979 non-null  int64
 60  GK Kicking        18979 non-null  int64
 61  GK Positioning    18979 non-null  int64
 62  GK Reflexes       18979 non-null  int64
 63  Total Stats       18979 non-null  int64
 64  Base Stats        18979 non-null  int64
 65  W/F               18979 non-null  object
 66  SM                18979 non-null  object
 67  A/W               18979 non-null  object
 68  D/W               18979 non-null  object
 69  IR                18979 non-null  object
 70  PAC               18979 non-null  int64
 71  SHO               18979 non-null  int64
 72  PAS               18979 non-null  int64
 73  DRI               18979 non-null  int64
 74  DEF               18979 non-null  int64
 75  PHY               18979 non-null  int64
 76  Hits              16384 non-null  object
dtypes: int64(54), object(23)
memory usage: 11.1+ MB

Both Height and weight appear as objects instead of int64, will fix that now

In [ ]:
df["Height"].value_counts()

Height
180cm    1474
178cm    1250
185cm    1182
183cm    1148
175cm    1091
         ...
5'4"        1
156cm       1
157cm       1
206cm       1
155cm       1
Name: count, Length: 62, dtype: int64

The "cm" on each row dont help, thus, I will remove them

In [ ]:
df["Height"]= df["Height"].str.replace("cm","")

In [ ]:
df["Height"].value_counts()

Height
180     1474
178     1250
185     1182
183     1148
175     1091
        ...
5'4"       1
156        1
157        1
206        1
155        1
Name: count, Length: 62, dtype: int64

In [ ]:
particular_key = df["Height"].str.contains('\'')
particular_key.value_counts()

Height
False    18939
True        40
Name: count, dtype: int64

Grab the rows that contain feet and inches and only display said rows

In [ ]:
df[df["Height"].str.contains('\'')]

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
793,110677,Moyá,Miguel Ángel Moyá Rumbo,https://cdn.sofifa.com/players/110/677/21_60.png,http://sofifa.com/player/110677/miguel-angel-m...,Spain,36,78,78,Real Sociedad,...,Medium,Medium,2 ★,82,72,80,78,39,79,14
847,166706,M. Škrtel,Martin Škrtel,https://cdn.sofifa.com/players/166/706/21_60.png,http://sofifa.com/player/166706/martin-skrtel/...,Slovakia,35,78,78,Medipol Başakşehir FK,...,Medium,High,3 ★,47,38,48,51,78,82,22
848,189068,B. Dost,Bas Dost,https://cdn.sofifa.com/players/189/068/21_60.png,http://sofifa.com/player/189068/bas-dost/210005/,Netherlands,31,78,78,Eintracht Frankfurt,...,Medium,Medium,3 ★,47,81,57,65,51,79,33
860,198031,Sérgio Oliveira,Sérgio Miguel Relvas de Oliveira,https://cdn.sofifa.com/players/198/031/21_60.png,http://sofifa.com/player/198031/sergio-miguel-...,Portugal,28,78,78,FC Porto,...,Medium,High,1 ★,58,77,82,75,66,68,41
861,190243,M. Hitz,Marwin Hitz,https://cdn.sofifa.com/players/190/243/21_60.png,http://sofifa.com/player/190243/marwin-hitz/21...,Switzerland,32,78,78,Borussia Dortmund,...,Medium,Medium,2 ★,79,77,63,80,44,79,17
862,194222,Laguardia,Víctor Laguardia Cisneros,https://cdn.sofifa.com/players/194/222/21_60.png,http://sofifa.com/player/194222/victor-laguard...,Spain,30,78,78,Deportivo Alavés,...,Medium,High,1 ★,51,46,55,51,80,78,3
863,194209,Y. El Arabi,Youssef El Arabi,https://cdn.sofifa.com/players/194/209/21_60.png,http://sofifa.com/player/194209/youssef-el-ara...,Morocco,33,78,78,Olympiacos CFP,...,High,Medium,2 ★,71,81,67,78,37,70,8
864,193601,G. Pezzella,Germán Pezzella,https://cdn.sofifa.com/players/193/601/21_60.png,http://sofifa.com/player/193601/german-pezzell...,Argentina,29,78,78,Fiorentina,...,Medium,Medium,1 ★,54,49,47,56,80,74,20
865,193352,R. Rodríguez,Ricardo Rodríguez,https://cdn.sofifa.com/players/193/352/21_60.png,http://sofifa.com/player/193352/ricardo-rodrig...,Switzerland,27,78,78,Torino,...,Medium,Medium,3 ★,71,67,76,74,77,74,36
866,193152,Herrerín,Iago Herrerín Buisán,https://cdn.sofifa.com/players/193/152/21_60.png,http://sofifa.com/player/193152/iago-herrerin-...,Spain,32,78,78,Athletic Club de Bilbao,...,Medium,Medium,1 ★,80,78,83,74,43,77,11
867,192546,E. Stevens,Enda Stevens,https://cdn.sofifa.com/players/192/546/21_60.png,http://sofifa.com/player/192546/enda-stevens/2...,Republic of Ireland,29,78,78,Sheffield United,...,Medium,Medium,1 ★,75,45,66,75,74,74,26
868,192123,C. Wood,Chris Wood,https://cdn.sofifa.com/players/192/123/21_60.png,http://sofifa.com/player/192123/chris-wood/210...,New Zealand,28,78,78,Burnley,...,High,Medium,1 ★,66,78,59,68,40,81,34
869,192086,A. Kokorin,Alexandr Kokorin,https://cdn.sofifa.com/players/192/086/21_60.png,http://sofifa.com/player/192086/alexandr-kokor...,Russia,29,78,78,Spartak Moscow,...,High,Medium,2 ★,81,77,72,81,43,69,18
871,192045,L. Rodríguez,Luis Rodríguez,https://cdn.sofifa.com/players/192/045/21_60.png,http://sofifa.com/player/192045/luis-rodriguez...,Mexico,29,78,78,Tigres U.A.N.L.,...,High,High,1 ★,84,64,72,75,72,77,32
872,189280,A. Westwood,Ashley Westwood,https://cdn.sofifa.com/players/189/280/21_60.png,http://sofifa.com/player/189280/ashley-westwoo...,England,30,78,78,Burnley,...,Medium,Medium,1 ★,59,62,79,73,74,76,17
873,196978,C. Wilson,Callum Wilson,https://cdn.sofifa.com/players/196/978/21_60.png,http://sofifa.com/player/196978/callum-wilson/...,England,28,78,78,Newcastle United,...,High,Medium,1 ★,82,77,65,76,39,74,62
874,188988,M. Lanzini,Manuel Lanzini,https://cdn.sofifa.com/players/188/988/21_60.png,http://sofifa.com/player/188988/manuel-lanzini...,Argentina,27,78,79,West Ham United,...,Medium,Medium,2 ★,76,72,78,82,32,47,29
875,173909,K. Boateng,Kevin-Prince Boateng,https://cdn.sofifa.com/players/173/909/21_60.png,http://sofifa.com/player/173909/kevin-prince-b...,Ghana,33,78,78,AC Monza,...,High,Medium,3 ★,64,78,77,80,65,74,38
876,188427,S. Lulić,Senad Lulić,https://cdn.sofifa.com/players/188/427/21_60.png,http://sofifa.com/player/188427/senad-lulic/21...,Bosnia Herzegovina,34,78,78,Lazio,...,High,High,2 ★,77,72,76,78,75,77,10
877,140293,A. Mirante,Antonio Mirante,https://cdn.sofifa.com/players/140/293/21_60.png,http://sofifa.com/player/140293/antonio-mirant...,Italy,36,78,78,Roma,...,Medium,Medium,2 ★,79,78,65,77,43,79,10
878,188268,L. Acosta,Lautaro Acosta,https://cdn.sofifa.com/players/188/268/21_60.png,http://sofifa.com/player/188268/lautaro-acosta...,Argentina,32,78,78,Club Atlético Lanús,...,High,High,1 ★,89,70,72,80,51,65,13
879,188042,M. Suárez,Matías Suárez,https://cdn.sofifa.com/players/188/042/21_60.png,http://sofifa.com/player/188042/matias-suarez/...,Argentina,32,78,78,River Plate,...,High,Medium,2 ★,76,77,76,82,45,74,17
880,188041,Rafael Carioca,Rafael de Souza Pereira,https://cdn.sofifa.com/players/188/041/21_60.png,http://sofifa.com/player/188041/rafael-de-souz...,Brazil,31,78,78,Tigres U.A.N.L.,...,Medium,Medium,1 ★,69,66,77,75,73,73,15
881,186547,M. Musacchio,Mateo Musacchio,https://cdn.sofifa.com/players/186/547/21_60.png,http://sofifa.com/player/186547/mateo-musacchi...,Argentina,29,78,78,Milan,...,Medium,Medium,3 ★,63,47,63,67,82,70,26
883,183353,Víctor Díaz,Víctor David Díaz Miguel,https://cdn.sofifa.com/players/183/353/21_60.png,http://sofifa.com/player/183353/victor-david-d...,Spain,32,78,78,Granada CF,...,Medium,High,1 ★,72,56,68,68,74,76,6
884,178250,P. Diop,Papakouli Diop,https://cdn.sofifa.com/players/178/250/21_60.png,http://sofifa.com/player/178250/papakouli-diop...,Senegal,34,78,78,SD Eibar,...,Medium,Medium,1 ★,41,66,68,67,78,85,16
885,178213,E. Capoue,Etienne Capoue,https://cdn.sofifa.com/players/178/213/21_60.png,http://sofifa.com/player/178213/etienne-capoue...,France,31,78,78,Watford,...,Medium,Medium,2 ★,51,71,73,70,77,77,13
886,175254,F. Caicedo,Felipe Caicedo,https://cdn.sofifa.com/players/175/254/21_60.png,http://sofifa.com/player/175254/felipe-caicedo...,Ecuador,31,78,78,Lazio,...,High,Medium,2 ★,73,76,71,75,44,80,20
887,183899,P. Piatti,Pablo Piatti,https://cdn.sofifa.com/players/183/899/21_60.png,http://sofifa.com/player/183899/pablo-piatti/2...,Argentina,31,78,78,Toronto FC,...,High,Medium,2 ★,83,75,75,79,47,54,12
888,173221,A. Candreva,Antonio Candreva,https://cdn.sofifa.com/players/173/221/21_60.png,http://sofifa.com/player/173221/antonio-candre...,Italy,33,78,78,Sampdoria,...,Medium,Medium,3 ★,72,78,77,79,61,65,31
889,158626,M. Debuchy,Mathieu Debuchy,https://cdn.sofifa.com/players/158/626/21_60.png,http://sofifa.com/player/158626/mathieu-debuch...,France,34,78,78,AS Saint-Étienne,...,High,Medium,3 ★,67,67,73,74,77,72,14
890,143001,C. Tévez,Carlos Tévez,https://cdn.sofifa.com/players/143/001/21_60.png,http://sofifa.com/player/143001/carlos-tevez/2...,Argentina,36,78,78,Boca Juniors,...,High,Low,3 ★,68,81,74,78,45,77,39
891,173208,D. Criscito,Domenico Criscito,https://cdn.sofifa.com/players/173/208/21_60.png,http://sofifa.com/player/173208/domenico-crisc...,Italy,33,78,78,Genoa,...,High,Medium,2 ★,73,61,76,71,77,74,12
892,143121,J. Sosa,José Sosa,https://cdn.sofifa.com/players/143/121/21_60.png,http://sofifa.com/player/143121/jose-sosa/210005/,Argentina,35,78,78,Fenerbahçe SK,...,Medium,Medium,2 ★,69,70,82,80,66,65,18
893,154472,Jorge Molina,Jorge Molina Vidal,https://cdn.sofifa.com/players/154/472/21_60.png,http://sofifa.com/player/154472/jorge-molina-v...,Spain,38,78,78,Granada CF,...,Medium,Medium,1 ★,36,82,67,70,42,73,11
894,146296,Andrés Fernández,Andrés Eduardo Fernández Moreno,https://cdn.sofifa.com/players/146/296/21_60.png,http://sofifa.com/player/146296/andres-eduardo...,Spain,33,78,78,SD Huesca,...,Medium,Medium,1 ★,80,75,68,79,56,76,10
895,171791,José Fonte,José Miguel da Rocha Fonte,https://cdn.sofifa.com/players/171/791/21_60.png,http://sofifa.com/player/171791/jose-miguel-da...,Portugal,36,78,78,LOSC Lille,...,Medium,High,3 ★,32,38,54,59,79,76,28
896,171897,A. Guardado,Andrés Guardado,https://cdn.sofifa.com/players/171/897/21_60.png,http://sofifa.com/player/171897/andres-guardad...,Mexico,33,78,78,Real Betis,...,Medium,Medium,3 ★,67,69,79,80,71,68,27
897,172962,V. Moses,Victor Moses,https://cdn.sofifa.com/players/172/962/21_60.png,http://sofifa.com/player/172962/victor-moses/2...,Nigeria,29,78,78,Chelsea,...,Medium,Medium,2 ★,76,69,74,81,73,69,40
898,142707,L. López,Lisandro López,https://cdn.sofifa.com/players/142/707/21_60.png,http://sofifa.com/player/142707/lisandro-lopez...,Argentina,37,78,78,Racing Club,...,High,High,2 ★,69,80,73,77,50,69,24

In [ ]:
import re
import numpy as np

def feet_to_cm(value):
  #extract the numbers
  numbers = re.match(r"(\d+)'(\d+)\"", value)
  if numbers:
    feet = int(numbers.group(1))
    inches = int(numbers.group(2))
    cm = ((feet*12) + inches)* 2.54
    return cm
  else:
    return value

In [ ]:
df[df["Height"].str.contains('\'')]["Height"]

793     6'2"
847     6'3"
848     6'5"
860    5'11"
861     6'4"
862     6'1"
863     6'0"
864     6'1"
865    5'11"
866     6'2"
867     6'0"
868     6'3"
869     6'0"
871    5'10"
872     5'9"
873    5'11"
874     5'6"
875     6'1"
876     6'0"
877     6'4"
878     5'7"
879     6'0"
880    5'11"
881    5'11"
883     6'0"
884    5'10"
885     6'3"
886     6'0"
887     5'4"
888    5'11"
889     5'9"
890     5'7"
891     6'0"
892    5'10"
893     6'2"
894     6'2"
895     6'3"
896     5'7"
897    5'10"
898     5'9"
Name: Height, dtype: object

In [ ]:
df[df["Height"].str.contains('\'')]["Height"].apply(feet_to_cm)

793    187.96
847    190.50
848    195.58
860    180.34
861    193.04
862    185.42
863    182.88
864    185.42
865    180.34
866    187.96
867    182.88
868    190.50
869    182.88
871    177.80
872    175.26
873    180.34
874    167.64
875    185.42
876    182.88
877    193.04
878    170.18
879    182.88
880    180.34
881    180.34
883    182.88
884    177.80
885    190.50
886    182.88
887    162.56
888    180.34
889    175.26
890    170.18
891    182.88
892    177.80
893    187.96
894    187.96
895    190.50
896    170.18
897    177.80
898    175.26
Name: Height, dtype: float64

In [ ]:
df["Height"] = df["Height"].apply(feet_to_cm)
df["Height"]

0        170
1        187
2        188
3        181
4        175
        ...
18974    178
18975    175
18976    179
18977    175
18978    188
Name: Height, Length: 18979, dtype: object

In [ ]:
df["Height"]

0        170
1        187
2        188
3        181
4        175
        ...
18974    178
18975    175
18976    179
18977    175
18978    188
Name: Height, Length: 18979, dtype: object

In [ ]:
df["Height"] = df["Height"].astype(int)

In [ ]:
df["Height"]

0        170
1        187
2        188
3        181
4        175
        ...
18974    178
18975    175
18976    179
18977    175
18978    188
Name: Height, Length: 18979, dtype: int64

Now work with weight

In [ ]:
df["Weight"].value_counts()

Weight
70kg      1495
75kg      1457
80kg      1108
72kg      1022
78kg       991
          ...
163lbs       1
110kg        1
107kg        1
50kg         1
53kg         1
Name: count, Length: 79, dtype: int64

There are some values in lb, thus, we have to convert them to kg and then delete "kg". After that, we can then convert the data type to int

In [ ]:
def lb_and_kg_to_numerical(value):

  if "lbs" in value:
    number = value.replace("lbs", "")
    number = float(number)
    kgs_value = number * 0.453592
    return kgs_value
  elif "kg" in value:
    kg_mod_value = value.replace("kg", "")
    return kg_mod_value
  else:
    return value

In [ ]:
df["Weight"]

0        72kg
1        83kg
2        87kg
3        70kg
4        68kg
         ...
18974    66kg
18975    65kg
18976    74kg
18977    69kg
18978    75kg
Name: Weight, Length: 18979, dtype: object

In [ ]:
df["Weight"] = df["Weight"].apply(lb_and_kg_to_numerical)

In [ ]:
df["Weight"]

0        72
1        83
2        87
3        70
4        68
         ..
18974    66
18975    65
18976    74
18977    69
18978    75
Name: Weight, Length: 18979, dtype: object

In [ ]:
df = df.rename(columns={"Weight": "Weight (in Kg)"})

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 77 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                18979 non-null  int64
 1   Name              18979 non-null  object
 2   LongName          18979 non-null  object
 3   photoUrl          18979 non-null  object
 4   playerUrl         18979 non-null  object
 5   Nationality       18979 non-null  object
 6   Age               18979 non-null  int64
 7   ↓OVA              18979 non-null  int64
 8   POT               18979 non-null  int64
 9   Club              18979 non-null  object
 10  Contract          18979 non-null  object
 11  Positions         18979 non-null  object
 12  Height            18979 non-null  int64
 13  Weight (in Kg)    18979 non-null  object
 14  Preferred Foot    18979 non-null  object
 15  BOV               18979 non-null  int64
 16  Best Position     18979 non-null  object
 17  Joined            18979 non-null  object
 18  Loan Date End     1013 non-null   object
 19  Value             18979 non-null  object
 20  Wage              18979 non-null  object
 21  Release Clause    18979 non-null  object
 22  Attacking         18979 non-null  int64
 23  Crossing          18979 non-null  int64
 24  Finishing         18979 non-null  int64
 25  Heading Accuracy  18979 non-null  int64
 26  Short Passing     18979 non-null  int64
 27  Volleys           18979 non-null  int64
 28  Skill             18979 non-null  int64
 29  Dribbling         18979 non-null  int64
 30  Curve             18979 non-null  int64
 31  FK Accuracy       18979 non-null  int64
 32  Long Passing      18979 non-null  int64
 33  Ball Control      18979 non-null  int64
 34  Movement          18979 non-null  int64
 35  Acceleration      18979 non-null  int64
 36  Sprint Speed      18979 non-null  int64
 37  Agility           18979 non-null  int64
 38  Reactions         18979 non-null  int64
 39  Balance           18979 non-null  int64
 40  Power             18979 non-null  int64
 41  Shot Power        18979 non-null  int64
 42  Jumping           18979 non-null  int64
 43  Stamina           18979 non-null  int64
 44  Strength          18979 non-null  int64
 45  Long Shots        18979 non-null  int64
 46  Mentality         18979 non-null  int64
 47  Aggression        18979 non-null  int64
 48  Interceptions     18979 non-null  int64
 49  Positioning       18979 non-null  int64
 50  Vision            18979 non-null  int64
 51  Penalties         18979 non-null  int64
 52  Composure         18979 non-null  int64
 53  Defending         18979 non-null  int64
 54  Marking           18979 non-null  int64
 55  Standing Tackle   18979 non-null  int64
 56  Sliding Tackle    18979 non-null  int64
 57  Goalkeeping       18979 non-null  int64
 58  GK Diving         18979 non-null  int64
 59  GK Handling       18979 non-null  int64
 60  GK Kicking        18979 non-null  int64
 61  GK Positioning    18979 non-null  int64
 62  GK Reflexes       18979 non-null  int64
 63  Total Stats       18979 non-null  int64
 64  Base Stats        18979 non-null  int64
 65  W/F               18979 non-null  object
 66  SM                18979 non-null  object
 67  A/W               18979 non-null  object
 68  D/W               18979 non-null  object
 69  IR                18979 non-null  object
 70  PAC               18979 non-null  int64
 71  SHO               18979 non-null  int64
 72  PAS               18979 non-null  int64
 73  DRI               18979 non-null  int64
 74  DEF               18979 non-null  int64
 75  PHY               18979 non-null  int64
 76  Hits              16384 non-null  object
dtypes: int64(55), object(22)
memory usage: 11.1+ MB

Now lets check the "Value", "Wage", and "Release Clause" columns

In [ ]:
df[["Value", "Wage", "Release Clause"]]

         Value   Wage Release Clause
0      €103.5M  €560K        €138.4M
1         €63M  €220K         €75.9M
2        €120M  €125K        €159.4M
3        €129M  €370K          €161M
4        €132M  €270K        €166.5M
...        ...    ...            ...
18974    €100K    €1K           €70K
18975    €130K   €500          €165K
18976    €120K   €500          €131K
18977    €100K    €2K           €88K
18978    €100K    €1K           €79K

[18979 rows x 3 columns]

In [ ]:
df[["Value", "Wage", "Release Clause"]].value_counts(ascending=True)

Value  Wage  Release Clause
€9M    €58K  €0                  1
       €55K  €0                  1
       €54K  €11.1M              1
       €53K  €0                  1
       €48K  €14.3M              1
                              ...
€725K  €500  €1.2M              21
€1M    €2K   €1.1M              22
€1.3M  €2K   €1.2M              25
€1.1M  €2K   €1.1M              32
€0     €0    €0                237
Name: count, Length: 13521, dtype: int64

In [ ]:
def monetary_to_numerical(value):
  value = str(value)
  if "€" in value:
    value = value.replace("€", "")
  if "K" in value:
    value = value.replace("K", "")
    value = float(value)
    value = value * 1000
    return value
  elif "M" in value:
    value = value.replace("M", "")
    value = float(value)
    value = value * 1000000
    return value
  else:
    return value

In [ ]:
df[["Value", "Wage", "Release Clause"]] = df[["Value", "Wage", "Release Clause"]].map(monetary_to_numerical)

In [ ]:
df[["Value", "Wage", "Release Clause"]]

             Value      Wage Release Clause
0      103500000.0  560000.0    138400000.0
1       63000000.0  220000.0     75900000.0
2      120000000.0  125000.0    159400000.0
3      129000000.0  370000.0    161000000.0
4      132000000.0  270000.0    166500000.0
...            ...       ...            ...
18974     100000.0    1000.0        70000.0
18975     130000.0       500       165000.0
18976     120000.0       500       131000.0
18977     100000.0    2000.0        88000.0
18978     100000.0    1000.0        79000.0

[18979 rows x 3 columns]

In [ ]:
df = df.rename(columns={"Value": "Value (In €)"})
df = df.rename(columns={"Wage": "Wage (In €)"})
df = df.rename(columns={"Release Clause": "Release Clause (In €)"})

In [ ]:
df

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,FC Barcelona,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,Juventus,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,Atlético Madrid,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,91,Manchester City,...,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,91,Paris Saint-Germain,...,High,Medium,5 ★,91,85,86,94,36,59,595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47,55,Wuhan Zall,...,Medium,Medium,1 ★,64,28,26,38,48,51,NaN
18975,258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47,67,Oldham Athletic,...,Medium,Medium,1 ★,64,40,48,49,35,45,NaN
18976,252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18,47,65,Derry City,...,Medium,Medium,1 ★,63,39,44,46,40,53,NaN
18977,243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20,47,57,Dalian YiFang FC,...,Medium,Medium,1 ★,58,49,41,49,30,44,NaN
18978,252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47,57,Dalian YiFang FC,...,Medium,Medium,1 ★,62,22,39,42,45,55,NaN

Remove all of the star value instances

In [ ]:
df["IR"].astype(str)
df["IR"]

0        5 ★
1        5 ★
2        3 ★
3        4 ★
4        5 ★
        ...
18974    1 ★
18975    1 ★
18976    1 ★
18977    1 ★
18978    1 ★
Name: IR, Length: 18979, dtype: object

In [ ]:
df["IR"]= df["IR"].str.replace("★", "")
df["IR"]= df["IR"].astype(int)
df["IR"]

0        5
1        5
2        3
3        4
4        5
        ..
18974    1
18975    1
18976    1
18977    1
18978    1
Name: IR, Length: 18979, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 77 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     18979 non-null  int64
 1   Name                   18979 non-null  object
 2   LongName               18979 non-null  object
 3   photoUrl               18979 non-null  object
 4   playerUrl              18979 non-null  object
 5   Nationality            18979 non-null  object
 6   Age                    18979 non-null  int64
 7   ↓OVA                   18979 non-null  int64
 8   POT                    18979 non-null  int64
 9   Club                   18979 non-null  object
 10  Contract               18979 non-null  object
 11  Positions              18979 non-null  object
 12  Height                 18979 non-null  int64
 13  Weight (in Kg)         18979 non-null  object
 14  Preferred Foot         18979 non-null  object
 15  BOV                    18979 non-null  int64
 16  Best Position          18979 non-null  object
 17  Joined                 18979 non-null  object
 18  Loan Date End          1013 non-null   object
 19  Value (In €)           18979 non-null  object
 20  Wage (In €)            18979 non-null  object
 21  Release Clause (In €)  18979 non-null  object
 22  Attacking              18979 non-null  int64
 23  Crossing               18979 non-null  int64
 24  Finishing              18979 non-null  int64
 25  Heading Accuracy       18979 non-null  int64
 26  Short Passing          18979 non-null  int64
 27  Volleys                18979 non-null  int64
 28  Skill                  18979 non-null  int64
 29  Dribbling              18979 non-null  int64
 30  Curve                  18979 non-null  int64
 31  FK Accuracy            18979 non-null  int64
 32  Long Passing           18979 non-null  int64
 33  Ball Control           18979 non-null  int64
 34  Movement               18979 non-null  int64
 35  Acceleration           18979 non-null  int64
 36  Sprint Speed           18979 non-null  int64
 37  Agility                18979 non-null  int64
 38  Reactions              18979 non-null  int64
 39  Balance                18979 non-null  int64
 40  Power                  18979 non-null  int64
 41  Shot Power             18979 non-null  int64
 42  Jumping                18979 non-null  int64
 43  Stamina                18979 non-null  int64
 44  Strength               18979 non-null  int64
 45  Long Shots             18979 non-null  int64
 46  Mentality              18979 non-null  int64
 47  Aggression             18979 non-null  int64
 48  Interceptions          18979 non-null  int64
 49  Positioning            18979 non-null  int64
 50  Vision                 18979 non-null  int64
 51  Penalties              18979 non-null  int64
 52  Composure              18979 non-null  int64
 53  Defending              18979 non-null  int64
 54  Marking                18979 non-null  int64
 55  Standing Tackle        18979 non-null  int64
 56  Sliding Tackle         18979 non-null  int64
 57  Goalkeeping            18979 non-null  int64
 58  GK Diving              18979 non-null  int64
 59  GK Handling            18979 non-null  int64
 60  GK Kicking             18979 non-null  int64
 61  GK Positioning         18979 non-null  int64
 62  GK Reflexes            18979 non-null  int64
 63  Total Stats            18979 non-null  int64
 64  Base Stats             18979 non-null  int64
 65  W/F                    18979 non-null  object
 66  SM                     18979 non-null  object
 67  A/W                    18979 non-null  object
 68  D/W                    18979 non-null  object
 69  IR                     18979 non-null  int64
 70  PAC                    18979 non-null  int64
 71  SHO                    18979 non-null  int64
 72  PAS                    18979 non-null  int64
 73  DRI                    18979 non-null  int64
 74  DEF                    18979 non-null  int64
 75  PHY                    18979 non-null  int64
 76  Hits                   16384 non-null  object
dtypes: int64(56), object(21)
memory usage: 11.1+ MB

take care of the remaining NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 77 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     18979 non-null  int64
 1   Name                   18979 non-null  object
 2   LongName               18979 non-null  object
 3   photoUrl               18979 non-null  object
 4   playerUrl              18979 non-null  object
 5   Nationality            18979 non-null  object
 6   Age                    18979 non-null  int64
 7   ↓OVA                   18979 non-null  int64
 8   POT                    18979 non-null  int64
 9   Club                   18979 non-null  object
 10  Contract               18979 non-null  object
 11  Positions              18979 non-null  object
 12  Height                 18979 non-null  int64
 13  Weight (in Kg)         18979 non-null  object
 14  Preferred Foot         18979 non-null  object
 15  BOV                    18979 non-null  int64
 16  Best Position          18979 non-null  object
 17  Joined                 18979 non-null  object
 18  Loan Date End          1013 non-null   object
 19  Value (In €)           18979 non-null  object
 20  Wage (In €)            18979 non-null  object
 21  Release Clause (In €)  18979 non-null  object
 22  Attacking              18979 non-null  int64
 23  Crossing               18979 non-null  int64
 24  Finishing              18979 non-null  int64
 25  Heading Accuracy       18979 non-null  int64
 26  Short Passing          18979 non-null  int64
 27  Volleys                18979 non-null  int64
 28  Skill                  18979 non-null  int64
 29  Dribbling              18979 non-null  int64
 30  Curve                  18979 non-null  int64
 31  FK Accuracy            18979 non-null  int64
 32  Long Passing           18979 non-null  int64
 33  Ball Control           18979 non-null  int64
 34  Movement               18979 non-null  int64
 35  Acceleration           18979 non-null  int64
 36  Sprint Speed           18979 non-null  int64
 37  Agility                18979 non-null  int64
 38  Reactions              18979 non-null  int64
 39  Balance                18979 non-null  int64
 40  Power                  18979 non-null  int64
 41  Shot Power             18979 non-null  int64
 42  Jumping                18979 non-null  int64
 43  Stamina                18979 non-null  int64
 44  Strength               18979 non-null  int64
 45  Long Shots             18979 non-null  int64
 46  Mentality              18979 non-null  int64
 47  Aggression             18979 non-null  int64
 48  Interceptions          18979 non-null  int64
 49  Positioning            18979 non-null  int64
 50  Vision                 18979 non-null  int64
 51  Penalties              18979 non-null  int64
 52  Composure              18979 non-null  int64
 53  Defending              18979 non-null  int64
 54  Marking                18979 non-null  int64
 55  Standing Tackle        18979 non-null  int64
 56  Sliding Tackle         18979 non-null  int64
 57  Goalkeeping            18979 non-null  int64
 58  GK Diving              18979 non-null  int64
 59  GK Handling            18979 non-null  int64
 60  GK Kicking             18979 non-null  int64
 61  GK Positioning         18979 non-null  int64
 62  GK Reflexes            18979 non-null  int64
 63  Total Stats            18979 non-null  int64
 64  Base Stats             18979 non-null  int64
 65  W/F                    18979 non-null  object
 66  SM                     18979 non-null  object
 67  A/W                    18979 non-null  object
 68  D/W                    18979 non-null  object
 69  IR                     18979 non-null  int64
 70  PAC                    18979 non-null  int64
 71  SHO                    18979 non-null  int64
 72  PAS                    18979 non-null  int64
 73  DRI                    18979 non-null  int64
 74  DEF                    18979 non-null  int64
 75  PHY                    18979 non-null  int64
 76  Hits                   16384 non-null  object
dtypes: int64(56), object(21)
memory usage: 11.1+ MB

Delete the "Loan Date End" column as at the end, it doesnt help at all and it has too many NaN values

In [ ]:
df = df.drop("Loan Date End", axis= 1)

In [ ]:
df

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,FC Barcelona,...,Medium,Low,5,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,Juventus,...,High,Low,5,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,Atlético Madrid,...,Medium,Medium,3,87,92,78,90,52,90,150
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,91,Manchester City,...,High,High,4,76,86,93,88,64,78,207
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,91,Paris Saint-Germain,...,High,Medium,5,91,85,86,94,36,59,595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47,55,Wuhan Zall,...,Medium,Medium,1,64,28,26,38,48,51,NaN
18975,258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47,67,Oldham Athletic,...,Medium,Medium,1,64,40,48,49,35,45,NaN
18976,252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18,47,65,Derry City,...,Medium,Medium,1,63,39,44,46,40,53,NaN
18977,243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20,47,57,Dalian YiFang FC,...,Medium,Medium,1,58,49,41,49,30,44,NaN
18978,252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47,57,Dalian YiFang FC,...,Medium,Medium,1,62,22,39,42,45,55,NaN